version: "3.8"
services:
  backend:
    build: .
#      context: deploy/backend
#      dockerfile: ../Dockerfile
    ports:
      - 80:80
    environment:
      - POSTGRES_DB=goorm
      - POSTGRES_USER=player
      - POSTGRES_PASSWORD=playerpw
    networks:
      - goorm-t1-network
    # JPA EntityManager 생성 시 DB 연결을 바탕으로 하기 때문에
    # 설정해주거나 서비스 순서를 바꿔야한다.
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    volumes:
      - goorm-t1-db:/var/lib/postgresql/data
    networks:
      - goorm-t1-network

    # 환경 변수
    environment:
      - POSTGRES_DB=goorm
      - POSTGRES_USER=player
      - POSTGRES_PASSWORD=playerpw
#      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password

    # 컨테이너 내부 간 통신만을 지원할때는 expose
    # 외부 접속 포트를 열어줄때는 ports 로 포트포워딩 해줘야한다.
    expose:
      - 5432
    ports:
      - 11001:5432

# 볼륨 설정
volumes:
  goorm-t1-db:

# 네트워크 설정
# 설정을 하지 않으면 default network 생성
# network-on, drive 설정등이 있지만 간단하게 기본 설정으로 진행
networks:
  goorm-t1-network:

#secrets:
#  db-password:
#    file: db/password.txt



