version: "3.8"
services:
  backend:
    build: .
#      context: deploy/backend  # 별도의 디렉토리에서 관리한다면 사용 예시로 놔둠
#      dockerfile: ../Dockerfile
    ports:
      - 80:80
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
    networks:
      - goorm-t1-network
    # JPA EntityManager 생성 시 DB 연결을 바탕으로 하기 때문에
    # 설정해주거나 서비스 순서를 바꿔야한다.
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    volumes:
      - goorm-t1-db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goorm-t1-network

    # 환경 변수
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    expose: # 컨테이너 내부 네트워크 연결 포트 (Spring Boot - DB)
      - 5432
    ports:  # 외부 포트포워딩 (DB Admin Tool 데이터 확인 목적으로 사용 중)
      - 11001:5432

# 볼륨 설정
volumes:
  goorm-t1-db:

# 네트워크 설정
networks:
  goorm-t1-network: # network-on, drive 설정등이 있지만 간단하게 기본 설정으로 진행

# 이름 지정
name: "goorm-task1"



