spring:
  datasource:
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}?characterEncoding=utf8&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false